plugins:
  wemix_enabled:
    default: false
    client: true
  wemix_client_id:
    default: ''
  wemix_tokens:
    client: true
    default: 'SampleERC20,MINCO'
  wemix_secret:
    default: ''
  wemix_chain:
    default: 'tornado'
  wemix_token:
    default: 'SampleERC20'
  binder_url:
    default: 'https://dev-binder.wemix.co/'
  topic_point:
    default: 50
  post_point:
    default: 10
